r <- getOption("repos")
r["CRAN"] <- "http://cran.r-project.org"
options(repos=r)

utils::install.packages("brms", dependencies=TRUE )
utils::install.packages("BAS", dependencies=TRUE )
utils::install.packages("blmeco", dependencies=TRUE )
utils::install.packages("breathteststan", dependencies=TRUE )
utils::install.packages("edstan", dependencies=TRUE )
utils::install.packages("idealstan", dependencies=TRUE )
utils::install.packages("rstansim", dependencies=TRUE )
utils::install.packages("rstantools", dependencies=TRUE )
utils::install.packages("tmbstan", dependencies=TRUE )
utils::install.packages("bang", dependencies=TRUE )
utils::install.packages("abc", dependencies=TRUE )
utils::install.packages("BAEssd", dependencies=TRUE )
utils::install.packages("BANOVA", dependencies=TRUE )
utils::install.packages("BayesBinMix", dependencies=TRUE )
utils::install.packages("BayesFM", dependencies=TRUE )
utils::install.packages("bayesloglin", dependencies=TRUE )
utils::install.packages("MCMCpack", dependencies=TRUE )